### ISSUE TITLE
Importing VTF - System Error: 0x00000002: The system cannot find the file specified.

### ISSUE THREAD

**Issue by Gnates** [REDxEYE/SourceIO#3] opened 2019-03-18 09:37 UTC
**Blender 2.80 Beta** [ Date: **2019-03-17** Hash: **9099305771ec** ]
SourceIO v**3.4.0** - b052680
Model Used (NSFW): https://sfmlab.com/item/2711/

**MDL** imported successfully.
Afterwards, I selected all **VTF textures** and imported them successfully.

I don't know how to import **VMT**, so I skipped it for now.

Then I clicked, File --> New --> General
This time I tried to import all **VTF textures** first before importing **MDL**, but then I got the error message below:
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\__init__.py", line 92, in execute
    self.load_alpha, self.only_alpha)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\SourceIO\vtf\import_vtf.py", line 23, in import_texture
    vtf_lib.get_last_error()))
Exception: Failed to load texture :Error:
Error opening file.

System Error: 0x00000002:
The system cannot find the file specified.



location: <unknown location>:-1
```
I might be wrong, but I think I can avoid the error if I import the individual **VTF textures** 1 at a time.

**Comment by ssllav** [comment] 2019-11-14 19:40
Firsrly select all VMT or VTF with press A hotkey and then with pressed Shift deselect and select again the first file (for example). Not sure about it was same error or other but it can help

**Comment by Kaitou3D** [comment] 2020-01-06 15:07
Just attempted to reproduce this bug, it seems to have been patched out. good to close this out chief

**Comment by 0Curtain0** [comment] 2020-01-17 06:27
Yes, **Gnates** was my old github account that I lost access to awhile ago. You can close this since I can't reproduce this problem in **v3.5.8**.

**Closed** 2020-06-27 17:51 UTC
Labels: bug
