### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'exists'

### ISSUE THREAD

**Issue by MechaXYZ** [REDxEYE/SourceIO#126] opened 2022-02-27 17:09 UTC
I don't know why this started to happen but I get this error when I try to import a mdl file:
Python: Traceback (most recent call last):
  File "/home/plasmations/.var/app/org.blender.Blender/config/blender/3.0/scripts/addons/SourceIO-master/blender_bindings/operators/source1_operators.py", line 55, in execute
    model_container = import_model_from_full_path(mdl_path, self.scale, self.create_flex_drivers,
  File "/home/plasmations/.var/app/org.blender.Blender/config/blender/3.0/scripts/addons/SourceIO-master/blender_bindings/source1/mdl/model_loader.py", line 31, in import_model_from_full_path
    assert vtx_file.exists(), f"failed to find vtx file {mdl_path.with_suffix('')}"

AttributeError: 'NoneType' object has no attribute 'exists'

location: unknown location :-1

**Debian 11 Linux 64bit
Blender v3.0.1 (Installed via Flatpak)
SourceIO v4.0.1**

**Comment by REDxEYE** [comment] 2022-03-08 12:35
This is related to case-sensetive filesystem on linux

**Comment by REDxEYE** [comment] 2022-03-16 09:34
Should be fixed in master branch

**Closed** 2022-03-24 21:03 UTC
Labels: case-sensetive filesystem issue

**Comment by redthing1** [comment] 2022-03-25 01:41
With SourceIO master on Blender 3.1:
![2022-03-24_18-41](https://user-images.githubusercontent.com/54390138/160037895-674ba99d-7ed4-4b49-bd0d-04d28ead62c5.png)

**Comment by EntityinArray** [comment] 2022-07-02 14:02
Happens for me on Windows with the recent version.
![image](https://user-images.githubusercontent.com/18554021/177004030-135c2102-94d5-4d19-8884-5c6efc1609bc.png)

**Comment by REDxEYE** [comment] 2022-07-02 14:04
Make sure that `.vtx` exists, it should be next to .mdl file

**Comment by EntityinArray** [comment] 2022-07-02 14:19
It does, the issue is probably happening because it's sw.vtx. I will try to rename the file and see if it helps
![image](https://user-images.githubusercontent.com/18554021/177004611-6754b9a3-5bf7-44ad-bc67-85a5b97befad.png)

**Comment by EntityinArray** [comment] 2022-07-02 14:20
Still facing the problem after renaming to "barney.vtx"

**Comment by REDxEYE** [comment] 2022-07-02 14:21
I don't think I have support for the software renderer version of vtx
Try renaming it to .dx90.vtx

**Comment by EntityinArray** [comment] 2022-07-02 14:23
Yay, that worked!
Thank you for quick replies and developing amazing software
