### ISSUE TITLE
Failed to find WorldNode resource

### ISSUE THREAD

**Issue by EviTRea** [REDxEYE/SourceIO#268] opened 2024-03-23 06:38 UTC
When trying to import any CS2 .vpk map with 5.3.0 addon and Blender 4.0.2, it prints:
```
Python: Traceback (most recent call last):
  File "/home/user/.var/app/org.blender.Blender/config/blender/4.0/scripts/addons/SourceIO/blender_bindings/operators/source2_operators.py", line 145, in execute
    load_map(model, ContentManager(), self.scale)
  File "/home/user/.var/app/org.blender.Blender/config/blender/4.0/scripts/addons/SourceIO/blender_bindings/source2/vwrld/loader.py", line 39, in load_map
    return import_world(world_resource, map_resource, cm, scale)
  File "/home/user/.var/app/org.blender.Blender/config/blender/4.0/scripts/addons/SourceIO/blender_bindings/source2/vwrld/loader.py", line 54, in import_world
    raise FileNotFoundError("Failed to find WorldNode resource")
FileNotFoundError: Failed to find WorldNode resource
```

Might be a Linux exclusive thing?
I thought it might be a flathub issue so I downloaded standalone 4.1 RC, same error popped up, so probably an addon problem
5.3.0 update was specifically for 4.0 so idk what happened here
Probably doesn't matter but here's my Blender generated system info:
[system-info.txt](https://github.com/REDxEYE/SourceIO/files/14730508/system-info.txt)

=================
Edit: Replace username with user for readability

**Comment by REDxEYE** [comment] 2024-03-23 10:13
I'm unable to reproduce on 5.3.0. Make sure that you're using up-to-date version of CS2

**Comment by EviTRea** [comment] 2024-03-23 11:07
> Make sure that you're using up-to-date version of CS2

It's up-to-date, I played MM just yesterday, and just to be sure I tried again just now and got the same result
I also tried copying the files into a desktop folder and import from there, nothing changes

Not that I think it matters at all, but here's my system spec:
Operating System: Fedora Linux 39
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.7.9-200.fc39.x86_64 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570 GAMING X

**Comment by REDxEYE** [comment] 2024-03-23 11:37
I had an old version of CS2. After updating, I was able to reproduce the issue. The fix has been pushed to master.

**Comment by REDxEYE** [comment] 2024-04-11 11:23
Just download https://github.com/REDxEYE/SourceIO/archive/refs/heads/master.zip

**Closed** 2024-04-13 17:23 UTC
