### ISSUE TITLE
Flex/Shapekeys do not always import correctly on clamped meshes

### ISSUE THREAD

**Issue by Da-Nuker** [REDxEYE/SourceIO#57] opened 2020-09-30 17:39 UTC
In the current version of SourceIO (3.7.1.1 and current github code), some Source1 MDL files with clamped/split meshes do not import all their Flex/ShapeKey vertex positions correctly, causing unexpected deformations among the clamped areas.

The same MDL files and process works correctly in previous versions of SourceIO (3.5.5 and 3.5.8).

**Comment by REDxEYE** [comment] 2020-10-31 17:18
Can you provide example models?

**Comment by Da-Nuker** [comment] 2020-10-31 19:29
Warning: NSFW models for debugging purposes only.

Tested on 3.8.2 on 2.90.1. Both meshes were joined and duplicate vertices merged after import.

https://sfmlab.com/project/30351/ , try shape key "LegFix140FW30SwNelsonL" 
https://sfmlab.com/project/30153/ , try shape key "boxyshape"

Both above models can import/merge correctly on 3.5.8 but are corrupted on the newer version.

**Comment by REDxEYE** [comment] 2020-11-04 20:17
Most of the time it can be fixed by joining clamped meshes with main  and removing doubles, I cannot find the root cause of this problem

**Comment by Da-Nuker** [comment] 2020-11-05 03:31
I agree most of the time it works, with the exception of models with high vertex count or large number of shape keys. 

As there is a walkaround for this (using an older version), I suggest keeping this issue here so other users facing the same issue can try the older version of SourceIO to see if it resolves the issue for them.

**Comment by REDxEYE** [comment] 2020-11-26 22:00
Should be now fixed, please try to import these models again

**Closed** 2020-11-26 22:44 UTC

**Comment by Da-Nuker** [comment] 2020-11-27 10:30
Confirmed problem has been resolved now. Thank you very much! :)
